### ISSUE TITLE
Failed to activate the linter-luacheck package

### ISSUE THREAD

**Issue by urzds** [AtomLinter/linter-luacheck#10]
[Enter steps to reproduce below:]

1. Uninstalled linter-luacheck (see #9)
2. Reinstalled linter-luacheck

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [linter-luacheck](https://github.com/AtomLinter/linter-luacheck) package, v1.1.4

### Stack Trace

Failed to activate the linter-luacheck package

```
At Cannot find module 'sb-callsite'

Error: Cannot find module 'sb-callsite'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.install (@HOME@/.atom/packages/linter-luacheck/node_modules/atom-package-deps/lib/main.js:25:20)
  at Object.module.exports.activate (@HOME@/.atom/packages/linter-luacheck/lib/init.coffee:42:34)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
  at /usr/share/atom/resources/app.asar/src/package.js:155:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:148:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```

### Commands

```
     -0:24.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 settings-view:open (atom-text-editor.editor)
  2x -0:17.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "linter-luacheck": {
    "globals": [
      "jit",
      "bit",
      "p",
      "exports"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.14.0
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.15.4
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-hy, v0.1.0
language-ini, v1.14.0
language-latex, v0.6.1
language-lua, v0.9.4
language-nftables, v0.2.1
language-ocaml, v1.1.2
language-opencl, v0.1.1
language-rust, v0.4.6
language-thrift, v1.0.2
language-tmux, v0.4.0
latex, v0.29.0
latexer, v0.3.0
linter, v1.11.3
linter-clang, v3.4.4
linter-clojure, v1.1.2
linter-csslint, v1.3.1
linter-gcc, v0.6.7
linter-glsl, v1.0.6
linter-htmlhint, v1.0.3
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-php, v1.1.8
linter-rust, v0.4.1
linter-tidy, v2.1.0
minimap, v4.19.0
nuclide, v0.119.0
pdf-view, v0.39.0
project-manager, v2.7.6
proto-repl, v0.15.2
proto-repl-charts, v0.1.0
tool-bar, v0.2.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Wow, can you try this and see if it fixes this error for you
```
cd ~/.atom/packages/linter-luacheck
npm install atom-package-deps@latest
```

**Comment by urzds** [comment]
After reloading Atom (Ctrl+Alt+R), this issue does not appear again.

**Comment by steelbrain** [comment]
Closing as an atom upgrade issue
