### ISSUE TITLE
Can't seem to find the file?

### ISSUE THREAD

**Issue by Inari-Whitebear** [AtomLinter/linter-luacheck#7]
So, I installed LuaCheck, have the .bat too and all, even added it to PATH, didn't work, tried to point it to the file with the config option, didn't work either :/
Not sure if it's an atom thingy not working... "where luacheck" in cmd finds it fine too

```
Error: The system cannot find the path specified.
    at parameters.exit (C:\Users\Inari\.atom\packages\linter-luacheck\node_modules\atom-linter\lib\helpers.js:75:20)
    at module.exports.BufferedProcess.handleEvents.triggerExitCallback (C:\Users\Inari\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Inari\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.global._handle.onexit (internal/child_process.js:200:12)
```

**Comment by xpol** [comment]
You you tried set `Executable` in linter-luacheck setting page?

**Comment by Inari-Whitebear** [comment]
Yeah, that didn't seem to help either.

**Comment by Arcanemagus** [comment]
Does `luacheck` work from a terminal? It looks like getting this properly installed on Windows is quite the undertaking.

**Comment by Inari-Whitebear** [comment]
Odd, seems it does not... I was assuming the "Can't find file" was from not being able to find the bath, but apparently it errors that always oO

**Comment by Positive07** [comment]
I have a similar problem:
```
Error: ""luacheck.bat"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
    at ChildProcess.<anonymous> (C:\Users\Pablo\.atom\packages\linter-luacheck\node_modules\atom-linter\node_modules\sb-exec\lib\index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
Windows 10
Atom 1.9.9
linter-luacheck 1.1.5
luacheck 0.15.1
LuaJIT 2.0.4

I can run `luacheck` directly from the command line without anything else, even without the `.bat` extension.

**Comment by Arcanemagus** [comment]
@Positive07 it sounds like you might be seeing something else. Can you put the output of `where.exe luacheck` (ie. the _full_ path) into the Executable Path setting?

**Comment by Positive07** [comment]
Thanks that actually fix it and I'm not having the other problems reported in this thread, I had to restart some times though, I also found a problem that said that `luacheck.lua` was not found and it was looking for it in my project directory instead of the luacheck directory, but all was gone once I made the change you proposed

**Comment by Positive07** [comment]
Due to lack of information and since there have been several changes to this package since a year ago I'll close this.

Anyone who has a similar issue please open a new one
